# Generated by Django 5.2.8 on 2025-11-26 06:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("deadline", models.DateTimeField()),
                (
                    "importance",
                    models.PositiveSmallIntegerField(
                        help_text="Importance level from 1 (low) to 10 (high)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "effort",
                    models.FloatField(
                        help_text="Estimated effort in hours",
                        validators=[django.core.validators.MinValueValidator(0.5)],
                    ),
                ),
                ("score", models.FloatField(default=0, editable=False)),
                ("completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-score", "deadline"],
            },
        ),
    ]
